# Generated by Django 4.1.7 on 2023-03-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillari', '0002_station_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_station', models.CharField(max_length=30)),
                ('return_station', models.CharField(max_length=30)),
                ('distance', models.IntegerField(null=True)),
                ('duration', models.IntegerField(null=True)),
            ],
        ),
    ]
