# Generated by Django 4.1.7 on 2023-03-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillari', '0003_journey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='distance',
            field=models.FloatField(null=True),
        ),
    ]
